/**
 * Represents an event generated by a provider. Providers have to keep track
 * of previously generated events themselves, or risk getting duplicated events.
 */
export interface Event {
    /**
     * An id identifying this event. IDs have to be unique within a single provider, but multiple providers
     * can use the same ID for an event (as long as the `provider` field differs).
     */
    id: string;

    /**
     * The title of the generated event.
     */
    title: string;

    /**
     * The URL of the generated event.
     */
    url: string;

    /**
     * A HTML body of the event, which is shown in the web view if the event is expanded.
     */
    body: string;

    /**
     * When this event happened. This is _not_ when the event was emitted, but rather when the source
     * of the event was created (creation time of an article, tweet timestamp, etc).
     */
    timestamp?: Date;

    /**
     * Additional metadata that can further identify this object. Optional, and is mainly used for client-side filtering.
     */
    metadata?: object;
}